FROM nginx:alpine

LABEL maintainer="Kondukto <dev@kondukto.io>"

WORKDIR /app 
COPY get.sh /app/get.sh

RUN rm /etc/nginx/conf.d/default.conf

RUN echo $'\n\
server {\n\
   listen 80 default_server;\n\
   listen [::]:80 default_server;\n\
   root /app;\n\
   server_name _;\n\
   location / {\n\
      sendfile   on;\n\
      try_files $uri /get.sh;\n\
   }\n\
}' > /etc/nginx/conf.d/default.conf

