name: Invicti ASPM Gosec Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

concurrency:
  group: ci-master-gosec-scan-1
  cancel-in-progress: true

jobs:
  go-sec_scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      INVICTI_ASPM_TOKEN: ${{ secrets.INVICTI_ASPM_TOKEN }}
      INVICTI_ASPM_HOST: ${{ secrets.INVICTI_ASPM_HOST }}
    name: Invicti ASPM GoSec Scan

    steps:
      - name: Configure Invicti ASPM CLI
        id: configure_invicti_aspm_cli
        run: |
          curl -sSL https://cli.kondukto.io | sh

      - name: Get Invicti ASPM CLI Version
        id: kdt_version
        run: |
          kdt version

      - name: Checkout Project
        id: checkout_project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          ref: master

      - name: Run Gosec Security Scanner
        id: run_gosec
        uses: securego/gosec@955a68d0d19f4afb7503068f95059f7d0c529017
        with:
          # we let the report trigger content trigger a failure using the GitHub Security features.
          args: "-no-fail -fmt json -out results.json ./..."

      - name: Archive GoSec Scan Results
        id: archive_gosec_results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: results.json
          path: results.json

      - name: Upload Gosec Scan Results To Invicti ASPM
        id: upload_gosec_results
        run: |
          kdt scan -p ${{ github.event.repository.name }} -t gosec -b ${{ github.ref_name }} -f results.json          
