name: Invicti ASPM Nancy Scan

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches:
      - master

concurrency:
  group: ci-master-nancy-scan-1
  cancel-in-progress: true

jobs:
  nancy_scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
      INVICTI_ASPM_TOKEN: ${{ secrets.INVICTI_ASPM_TOKEN }}
      INVICTI_ASPM_HOST: ${{ secrets.INVICTI_ASPM_HOST }}
    name: Invicti ASPM Nancy Scan

    steps:
      - name: Configure Invicti ASPM CLI
        id: configure_invicti_aspm_cli
        run: |
          curl -sSL https://cli.kondukto.io | sh

      - name: Get Invicti ASPM CLI Version
        id: kdt_version
        run: |
          kdt version

      - name: Checkout Project
        id: checkout_project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          repository: kondukto-io/kdt
          ref: master

      - name: Setup Go
        id: setup_go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b
        with:
          go-version: 1.23
          cache: true
          cache-dependency-path: ./go.sum

      - name: Run Nancy Security Scanner
        continue-on-error: true
        id: run_nancy
        run: |
          docker pull sonatypecommunity/nancy:latest
          go list -json -deps ./... | docker run -i sonatypecommunity/nancy sleuth --output json-pretty > results.json

      - name: Archive Nancy Scan Results
        id: archive_nancy_results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: results.json
          path: results.json

      - name: Upload Nancy Scan Results To Invicti ASPM
        id: upload_nancy_results
        run: |
          kdt scan -p ${{ github.event.repository.name }} -t nancy -b ${{ github.ref_name }} -f results.json          
